apiVersion: v2
name: kkowa-server
version: "0.1.0"
description: Application chart for core server component of kkowa.
type: application
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    repository: "https://charts.bitnami.com/bitnami"
    version: "10.16.1"
    condition: postgresql.enabled
  - name: redis
    repository: "https://charts.bitnami.com/bitnami"
    version: "15.7.5"
    condition: redis.enabled
  - name: rabbitmq
    repository: "https://charts.bitnami.com/bitnami"
    version: "8.26.1"
    condition: rabbitmq.enabled
