# -- https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values
global:
  {}
  # -- Pull secrets to use, if chart's `imagePullSecrets` not set.
  # imagePullSecrets:

# -- https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies
# tags:

# -- https://helm.sh/docs/topics/charts/#using-the-exports-format
# exports:

# -- Override common name.
# nameOverride:

# -- Override fully qualified name.
# fullnameOverride:

# -- Common options to apply all resources.
common:
  {}
  # -- Common labels for all resources.
  # labels:

  # -- Common annotations for all resources, except resources has its own annotations config.
  # annotations:

# -- Application service account to use.
serviceAccount:
  # -- Whether create service account or not.
  create: true

  # -- Name of service account to use or create.
  # name:

  # -- Annotations to set to service account if creating.
  # annotations:

# -- Image pull secrets.
imagePullSecrets: []

# -- Overall application configurations.
app:
  # -- Application image.
  image:
    # -- Image repository to use.
    repository: registry.gitlab.com/kkowa/apps/server

    # -- Image tag to use; defaults to chart app version.
    # tag:

    # -- Image pull policy.
    pullPolicy: Always

  # -- Application configs.
  config:
    {}
    # -- Secret key for server. Will be generated automatically if not exists, and use existing one if already exists.
    # secretKey:

    # -- PostgreSQL database server URL. Will be rendered if template.
    # databaseURL:

    # -- Redis cache server URL. Will be rendered if template.
    # cacheURL:

    # -- Message broker URL for Celery message queue. Will be rendered if template.
    # messageBrokerURL:

    # -- Crawler gRPC service URL. Will be rendered if template.
    # crawlerURL:

  # -- Components in application.
  components:
    # -- Core server component; e.g web pages, APIs.
    server:
      # -- Replica count to create.
      replicas: 1

      # -- Whether automount service acount token. Defaults to false.
      # automountServiceAccountToken:

      # -- Pod security context.
      #    https://kubernetes.io/docs/concepts/security/pod-security-standards/
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      # -- Common container options.
      container:
        # -- Container security context.
        #    https://kubernetes.io/docs/concepts/security/pod-security-standards/
        securityContext:
          capabilities:
            drop:
              - ALL

          runAsUser: 10000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

        # -- Container resource quota.
        #    https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 768Mi

      # -- Auto scaling (HPA) options.
      #    https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/
      autoscaling:
        # -- Whether enable auto scaling or not. Disabled by default.
        enabled: false

        # -- Minimum of replicas.
        # min: 1

        # -- Maximum of replicas.
        # max: 3

        # -- Metrics used to calculate desired replica count.
        #    https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec
        # metrics:
        #   - type: Resource
        #     resource:
        #       name: cpu
        #       target:
        #         type: Utilization
        #         averageUtilization: 80

        # -- Detailed behavior of autoscaling.
        #    https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec
        # behavior:

        # -- Current status of auto scaler.
        #    https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerStatus
        # status:

    # -- Background celery workers. Internal schema is same for server component.
    worker:
      replicas: 1
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      container:
        securityContext:
          capabilities:
            drop:
              - ALL

          runAsUser: 10000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi

      autoscaling:
        enabled: false

    # -- Periodic scheduler for celery workers. Internal schema is same to server or worker component, except replication options.
    periodicScheduler:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      container:
        securityContext:
          capabilities:
            drop:
              - ALL

          runAsUser: 10000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi

# -- Application service to expose.
service:
  # -- Service type.
  type: ClusterIP

  # -- Service port.
  port: 8000

# =====================================================================================================================
# Subcharts
# =====================================================================================================================
# -- PostgreSQL subchart for application database.
#    https://artifacthub.io/packages/helm/bitnami/postgresql
postgresql:
  # -- Whether enable subchart.
  enabled: true

  nameOverride: database
  postgresqlPassword: "password"

# -- Redis subchart for application cache backend.
#    https://artifacthub.io/packages/helm/bitnami/redis
redis:
  # -- Whether enable subchart.
  enabled: true

  nameOverride: cache
  architecture: standalone
  auth:
    enabled: false

# -- RabbitMQ subchart for application message broker.
#    https://artifacthub.io/packages/helm/bitnami/rabbitmq
rabbitmq:
  # -- Whether enable subchart.
  enabled: true

  nameOverride: message-broker
  auth:
    password: "password"
