# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly

  - package-ecosystem: gitsubmodule
    directory: /
    target-branch: develop
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    target-branch: develop
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
