# Generated by Django 4.1 on 2022-08-13 13:08

from django.db import migrations
import src.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", src.apps.users.models.UserManager()),
            ],
        ),
    ]
