# Generated by Django 4.1 on 2022-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification datetime of folder.", verbose_name="last modified at"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, help_text="User's real name.", max_length=255, verbose_name="name of user"
            ),
        ),
    ]
