# Generated by Django 4.1 on 2022-08-17 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="key",
            field=models.CharField(
                blank=True, help_text="Value of token.", max_length=255, unique=True, verbose_name="key"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="owner",
            field=models.ForeignKey(
                help_text="Token's owner.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="token owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="token",
            constraint=models.CheckConstraint(
                check=models.Q(("valid_until__gt", django.db.models.functions.datetime.Now())),
                name="users_token_valid_until_must_be_future",
            ),
        ),
    ]
