exclude: |
  (?x)(
    ^idl/
    | ^.*/migrations/
    | ^_generated/
  )
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Prerequisites checkers
  - repo: local
    hooks:
      - id: generate
        name: Generate codes from schemas
        language: system
        types: [directory]
        pass_filenames: false
        entry: make generate

      - id: django-migration
        name: Check migrations created for model changes
        language: system
        types: [python]
        pass_filenames: false
        entry: poetry run python manage.py makemigrations
        args: [--check, --dry-run]

  # Formatters
  - repo: local
    hooks:
      - id: black
        name: Format with Black
        language: system
        types: [python]
        entry: poetry run black

      - id: pycln
        name: Remove unused imports with pycln
        language: system
        types: [python]
        entry: poetry run pycln

      - id: isort
        name: Format with isort
        language: system
        types: [python]
        entry: poetry run isort

  # Linters
  - repo: local
    hooks:
      - id: flake8
        name: Lint with Flake8
        language: system
        types: [python]
        entry: poetry run flake8

      - id: pydocstyle
        name: Lint with pydocstyle
        language: system
        types: [python]
        entry: poetry run pydocstyle

      - id: mypy
        name: Type check with Mypy
        language: system
        types: [python]
        entry: poetry run mypy
        args: [--show-error-codes, --pretty]

      - id: pytest
        name: Test with pytest
        language: system
        types: [python]
        pass_filenames: false
        entry: poetry run pytest

  # Post processors
  - repo: local
    hooks:
      - id: schema-export
        name: Generate service schemas
        language: system
        types: [python]
        pass_filenames: false
        entry: make schema-export
