apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}

  {{- with .Values.common.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ include "app.config.secretKey" . | b64enc | quote }}

  DATABASE_URL: {{ include "app.config.databaseURL" . | b64enc | quote }}
  CACHE_URL: {{ include "app.config.cacheURL" . | b64enc | quote }}
  MESSAGE_BROKER_URL: {{ include "app.config.messageBrokerURL" . | b64enc | quote }}

  MAILGUN_API_KEY: ""
