# Generated by Django 4.1 on 2022-08-09 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Name of folder to display.", max_length=512, verbose_name="name of Folder"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation datetime of folder.", verbose_name="created at"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last modification datetime of folder.",
                        verbose_name="last modified at",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Folder's owner.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "created"),
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "data",
                    models.JSONField(
                        blank=True, help_text="Document data in JSON format.", null=True, verbose_name="data"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation datetime of document.", verbose_name="created at"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last modification datetime of document.",
                        verbose_name="last modified at",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        help_text="Document folder it belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.folder",
                        verbose_name="folder",
                    ),
                ),
            ],
            options={
                "ordering": ("created",),
            },
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(fields=("owner", "name"), name="documents_folder_unique_per_user"),
        ),
    ]
