# Generated by Django 4.1 on 2022-08-13 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                help_text="Document folder it belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="documents.folder",
                verbose_name="folder",
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(
                help_text="Name of folder to display.", max_length=64, verbose_name="name of folder"
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="owner",
            field=models.ForeignKey(
                help_text="Folder's owner.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
    ]
