# Generated by Django 4.1 on 2022-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_folder_alter_folder_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ("created",), "verbose_name": "document", "verbose_name_plural": "documents"},
        ),
        migrations.AlterModelOptions(
            name="folder",
            options={"ordering": ("name", "created"), "verbose_name": "folder", "verbose_name_plural": "folders"},
        ),
        migrations.AlterField(
            model_name="document",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Creation datetime of folder.", verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification datetime of folder.", verbose_name="last modified at"
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="name",
            field=models.CharField(
                help_text="Name of folder to display.", max_length=50, verbose_name="name of folder"
            ),
        ),
    ]
